[project]
name = "yolo-project"
version = "0.1.0"
description = "Toml file for all yolo training scripts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "ipykernel>=6.29.5",
  "ipywidgets>=8.1.7",
  "pydantic>=2.11.7",
  "roboflow>=1.1.66",
  "scikit-learn>=1.7.0",
  "supervision>=0.25.1",
  "tensorboard>=2.20.0",
  "torch>=2.2.0",
  "torchaudio>=2.6.0",
  "torchvision>=0.21.0",
  "ultralytics<=8.3.40",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu124" },
]
torchvision = [
    { index = "pytorch-cu124" },
]
torchaudio = [
    { index = "pytorch-cu124" },
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
